# Generated by Django 5.2.4 on 2025-07-07 05:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Account",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=20, unique=True)),
                ("name", models.CharField(max_length=50)),
                ("description", models.TextField(blank=True)),
                (
                    "order",
                    models.IntegerField(
                        default=0, help_text="Controls ordering in UIs"
                    ),
                ),
            ],
            options={
                "ordering": ["order", "code"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Constant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("value", models.DecimalField(decimal_places=6, max_digits=18)),
            ],
        ),
        migrations.CreateModel(
            name="CostCenter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=20, unique=True)),
                ("name", models.CharField(max_length=50)),
                ("description", models.TextField(blank=True)),
                (
                    "order",
                    models.IntegerField(
                        default=0, help_text="Controls ordering in UIs"
                    ),
                ),
            ],
            options={
                "ordering": ["order", "code"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="GlobalVariable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True)),
                ("value", models.DecimalField(decimal_places=6, max_digits=18)),
            ],
        ),
        migrations.CreateModel(
            name="InternalOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=20, unique=True)),
                ("name", models.CharField(max_length=50)),
                ("description", models.TextField(blank=True)),
                (
                    "order",
                    models.IntegerField(
                        default=0, help_text="Controls ordering in UIs"
                    ),
                ),
                ("cc_code", models.CharField(blank=True, max_length=10)),
            ],
            options={
                "ordering": ["order", "code"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="KeyFigure",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=100, unique=True)),
                ("name", models.CharField(max_length=200)),
                ("is_percent", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Period",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=2, unique=True)),
                ("name", models.CharField(max_length=10)),
                ("order", models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="PlanningLayout",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=100, unique=True)),
                ("title", models.CharField(max_length=200)),
                ("domain", models.CharField(max_length=100)),
                ("default", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="SLAProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("response_time", models.DurationField()),
                ("resolution_time", models.DurationField()),
                ("availability", models.DecimalField(decimal_places=3, max_digits=5)),
                ("description", models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="UnitOfMeasure",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=10, unique=True)),
                ("name", models.CharField(max_length=50)),
                (
                    "is_base",
                    models.BooleanField(
                        default=False, help_text="Target unit for conversion rates"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Version",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=20, unique=True)),
                ("name", models.CharField(max_length=50)),
                ("description", models.TextField(blank=True)),
                (
                    "order",
                    models.IntegerField(
                        default=0, help_text="Controls ordering in UIs"
                    ),
                ),
            ],
            options={
                "ordering": ["order", "code"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Year",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=20, unique=True)),
                ("name", models.CharField(max_length=50)),
                ("description", models.TextField(blank=True)),
                (
                    "order",
                    models.IntegerField(
                        default=0, help_text="Controls ordering in UIs"
                    ),
                ),
            ],
            options={
                "ordering": ["order", "code"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="DataRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("description", models.CharField(blank=True, max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Formula",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "expression",
                    models.TextField(
                        help_text="Supports conditional logic, loops, and aggregation."
                    ),
                ),
                (
                    "dimensions",
                    models.ManyToManyField(
                        help_text="Multiple dimensions for looping",
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "layout",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bps.planninglayout",
                    ),
                ),
                (
                    "reference_version",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="bps.version",
                    ),
                ),
                (
                    "reference_year",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="bps.year",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FormulaRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("run_at", models.DateTimeField(auto_now_add=True)),
                ("preview", models.BooleanField(default=False)),
                (
                    "formula",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="bps.formula"
                    ),
                ),
                (
                    "run_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OrgUnit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("path", models.CharField(max_length=255, unique=True)),
                ("depth", models.PositiveIntegerField()),
                ("numchild", models.PositiveIntegerField(default=0)),
                ("code", models.CharField(max_length=20, unique=True)),
                ("name", models.CharField(max_length=50)),
                ("description", models.TextField(blank=True)),
                (
                    "order",
                    models.IntegerField(
                        default=0, help_text="Controls ordering in UIs"
                    ),
                ),
                ("cc_code", models.CharField(blank=True, max_length=10)),
                (
                    "head_user",
                    models.ForeignKey(
                        blank=True,
                        help_text="OrgUnit lead who must draft and approve",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PlanningFact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "driver_refs",
                    models.JSONField(
                        default=dict,
                        help_text="e.g. {'Position':123, 'SkillGroup':'Developer'}",
                    ),
                ),
                (
                    "value",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                (
                    "ref_value",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                (
                    "account",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="bps.account",
                    ),
                ),
                (
                    "key_figure",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="bps.keyfigure"
                    ),
                ),
                (
                    "org_unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="bps.orgunit"
                    ),
                ),
                (
                    "period",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="bps.period"
                    ),
                ),
                (
                    "request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="bps.datarequest",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FormulaRunEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=100)),
                ("old_value", models.DecimalField(decimal_places=6, max_digits=18)),
                ("new_value", models.DecimalField(decimal_places=6, max_digits=18)),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entries",
                        to="bps.formularun",
                    ),
                ),
                (
                    "record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bps.planningfact",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PlanningKeyFigure",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=100)),
                ("label", models.CharField(max_length=100)),
                ("is_editable", models.BooleanField(default=True)),
                ("is_computed", models.BooleanField(default=False)),
                ("formula", models.TextField(blank=True)),
                (
                    "layout",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="key_figures",
                        to="bps.planninglayout",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PlanningFunction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                (
                    "function_type",
                    models.CharField(
                        choices=[
                            ("COPY", "Copy"),
                            ("DISTRIBUTE", "Distribute"),
                            ("CURRENCY_CONVERT", "Currency Convert"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "parameters",
                    models.JSONField(
                        default=dict,
                        help_text='\n            COPY: { "from_version": <vid>, "to_version": <vid>, "year":<y>, "period":"01" }  \n            DISTRIBUTE: { "by":"OrgUnit", "reference_data":"2024 Actuals" }  \n            CURRENCY_CONVERT: { "target_uom":"USD" }\n        ',
                    ),
                ),
                (
                    "layout",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bps.planninglayout",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PlanningDimension",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("label", models.CharField(max_length=100)),
                ("is_row", models.BooleanField(default=False)),
                ("is_column", models.BooleanField(default=False)),
                ("is_filter", models.BooleanField(default=True)),
                ("is_editable", models.BooleanField(default=False)),
                ("required", models.BooleanField(default=True)),
                ("data_source", models.CharField(max_length=100)),
                (
                    "layout",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dimensions",
                        to="bps.planninglayout",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PlanningLayoutYear",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "header_dims",
                    models.JSONField(
                        default=dict, help_text="e.g. {'Company':'ALL','Region':'EMEA'}"
                    ),
                ),
                (
                    "layout",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="per_year",
                        to="bps.planninglayout",
                    ),
                ),
                ("org_units", models.ManyToManyField(blank=True, to="bps.orgunit")),
                (
                    "row_dims",
                    models.ManyToManyField(blank=True, to="contenttypes.contenttype"),
                ),
                (
                    "version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="bps.version"
                    ),
                ),
                (
                    "year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="bps.year"
                    ),
                ),
            ],
            options={
                "unique_together": {("layout", "year", "version")},
            },
        ),
        migrations.CreateModel(
            name="PlanningSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("D", "Draft"),
                            ("B", "Return Back"),
                            ("C", "Completed"),
                            ("R", "Review"),
                            ("F", "Frozen"),
                        ],
                        default="D",
                        max_length=1,
                    ),
                ),
                ("frozen_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "frozen_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "layout_year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to="bps.planninglayoutyear",
                    ),
                ),
                (
                    "org_unit",
                    models.ForeignKey(
                        help_text="Owner of this session",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bps.orgunit",
                    ),
                ),
            ],
            options={
                "unique_together": {("layout_year", "org_unit")},
            },
        ),
        migrations.AddField(
            model_name="planningfact",
            name="session",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="bps.planningsession"
            ),
        ),
        migrations.AddField(
            model_name="datarequest",
            name="session",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="requests",
                to="bps.planningsession",
            ),
        ),
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=20, unique=True)),
                ("name", models.CharField(max_length=50)),
                ("description", models.TextField(blank=True)),
                (
                    "order",
                    models.IntegerField(
                        default=0, help_text="Controls ordering in UIs"
                    ),
                ),
                ("category", models.CharField(max_length=50)),
                ("subcategory", models.CharField(max_length=50)),
                (
                    "criticality",
                    models.CharField(
                        choices=[("H", "High"), ("M", "Medium"), ("L", "Low")],
                        max_length=1,
                    ),
                ),
                (
                    "sla_response",
                    models.DurationField(help_text="e.g. PT2H for 2 hours"),
                ),
                (
                    "sla_resolution",
                    models.DurationField(help_text="e.g. PT4H for 4 hours"),
                ),
                (
                    "availability",
                    models.DecimalField(
                        decimal_places=3, help_text="e.g. 99.900", max_digits=5
                    ),
                ),
                (
                    "support_hours",
                    models.CharField(
                        choices=[
                            ("24x7", "24×7"),
                            ("9x5", "9×5 Mon–Fri"),
                            ("custom", "Custom"),
                        ],
                        max_length=10,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "orgunit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="bps.orgunit",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "related_services",
                    models.ManyToManyField(blank=True, to="bps.service"),
                ),
            ],
            options={
                "ordering": ["category", "subcategory", "code"],
            },
        ),
        migrations.AddField(
            model_name="planningfact",
            name="service",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="bps.service",
            ),
        ),
        migrations.CreateModel(
            name="CBU",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=20, unique=True)),
                ("name", models.CharField(max_length=50)),
                ("description", models.TextField(blank=True)),
                (
                    "order",
                    models.IntegerField(
                        default=0, help_text="Controls ordering in UIs"
                    ),
                ),
                ("group", models.CharField(blank=True, max_length=50)),
                (
                    "tier",
                    models.CharField(
                        choices=[("1", "Tier-1"), ("2", "Tier-2"), ("3", "Tier-3")],
                        max_length=1,
                    ),
                ),
                ("region", models.CharField(blank=True, max_length=50)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "sla_profile",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="bps.slaprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "code"],
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="planningfact",
            name="ref_uom",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="bps.unitofmeasure",
            ),
        ),
        migrations.AddField(
            model_name="planningfact",
            name="uom",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="bps.unitofmeasure",
            ),
        ),
        migrations.AddField(
            model_name="keyfigure",
            name="default_uom",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="bps.unitofmeasure",
            ),
        ),
        migrations.CreateModel(
            name="UserMaster",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cost_center",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="bps.costcenter",
                    ),
                ),
                (
                    "org_unit",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="bps.orgunit",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="planningfact",
            name="version",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="bps.version"
            ),
        ),
        migrations.CreateModel(
            name="ReferenceData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                (
                    "source_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="bps.version"
                    ),
                ),
                (
                    "source_year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="bps.year"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="planningfact",
            name="year",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="bps.year"
            ),
        ),
        migrations.CreateModel(
            name="PeriodGrouping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "months_per_bucket",
                    models.PositiveSmallIntegerField(
                        choices=[(1, "Monthly"), (3, "Quarterly"), (6, "Half-Year")]
                    ),
                ),
                ("label_prefix", models.CharField(default="", max_length=5)),
                (
                    "layout_year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="period_groupings",
                        to="bps.planninglayoutyear",
                    ),
                ),
            ],
            options={
                "unique_together": {("layout_year", "months_per_bucket")},
            },
        ),
        migrations.CreateModel(
            name="SubFormula",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "expression",
                    models.TextField(
                        help_text="Expression using other constants/sub-formulas, e.g. [Year=2025]?.[Qty] * TAX_RATE"
                    ),
                ),
                (
                    "layout",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subformulas",
                        to="bps.planninglayout",
                    ),
                ),
            ],
            options={
                "unique_together": {("layout", "name")},
            },
        ),
        migrations.CreateModel(
            name="ConversionRate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "factor",
                    models.DecimalField(
                        decimal_places=6,
                        help_text="Multiply a from_uom value by this to get to_uom",
                        max_digits=18,
                    ),
                ),
                (
                    "from_uom",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conv_from",
                        to="bps.unitofmeasure",
                    ),
                ),
                (
                    "to_uom",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conv_to",
                        to="bps.unitofmeasure",
                    ),
                ),
            ],
            options={
                "unique_together": {("from_uom", "to_uom")},
            },
        ),
        migrations.AddIndex(
            model_name="planningfact",
            index=models.Index(
                fields=["year", "version", "org_unit"],
                name="bps_plannin_year_id_fb22c7_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="planningfact",
            index=models.Index(
                fields=["key_figure"], name="bps_plannin_key_fig_8c01b3_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="planningfact",
            unique_together={
                (
                    "request",
                    "version",
                    "year",
                    "period",
                    "org_unit",
                    "service",
                    "account",
                    "key_figure",
                    "driver_refs",
                )
            },
        ),
    ]
