# Generated by Django 5.2.4 on 2025-07-25 05:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bps", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="ratecard",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="ratecard",
            name="hourly_rate",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="ratecard",
            name="year",
            field=models.ForeignKey(
                default=2025, on_delete=django.db.models.deletion.CASCADE, to="bps.year"
            ),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name="ratecard",
            unique_together={("year", "skill", "level", "resource_type", "country")},
        ),
    ]
