# Generated by Django 5.2.5 on 2025-08-18 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bps", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="dimensionkey",
            name="is_active",
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
