# Generated by Django 5.2.1 on 2025-07-11 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bps", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="planninglayout",
            old_name="title",
            new_name="name",
        ),
    ]
