# Generated by Django 5.2.4 on 2025-07-28 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bps", "0002_auto_20250728_0030"),
    ]

    operations = [
        migrations.CreateModel(
            name="PivotedPlanningFact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version", models.CharField(max_length=50)),
                ("year", models.IntegerField()),
                ("org_unit", models.CharField(max_length=50)),
                ("service", models.CharField(max_length=50)),
                ("account", models.CharField(max_length=50)),
                ("key_figure", models.CharField(max_length=50)),
                ("v01", models.FloatField(blank=True, null=True)),
                ("v02", models.FloatField(blank=True, null=True)),
                ("v03", models.FloatField(blank=True, null=True)),
                ("v04", models.FloatField(blank=True, null=True)),
                ("v05", models.FloatField(blank=True, null=True)),
                ("v06", models.FloatField(blank=True, null=True)),
                ("v07", models.FloatField(blank=True, null=True)),
                ("v08", models.FloatField(blank=True, null=True)),
                ("v09", models.FloatField(blank=True, null=True)),
                ("v10", models.FloatField(blank=True, null=True)),
                ("v11", models.FloatField(blank=True, null=True)),
                ("v12", models.FloatField(blank=True, null=True)),
                ("r01", models.FloatField(blank=True, null=True)),
                ("r02", models.FloatField(blank=True, null=True)),
                ("r03", models.FloatField(blank=True, null=True)),
                ("r04", models.FloatField(blank=True, null=True)),
                ("r05", models.FloatField(blank=True, null=True)),
                ("r06", models.FloatField(blank=True, null=True)),
                ("r07", models.FloatField(blank=True, null=True)),
                ("r08", models.FloatField(blank=True, null=True)),
                ("r09", models.FloatField(blank=True, null=True)),
                ("r10", models.FloatField(blank=True, null=True)),
                ("r11", models.FloatField(blank=True, null=True)),
                ("r12", models.FloatField(blank=True, null=True)),
                ("total_value", models.FloatField(blank=True, null=True)),
                ("total_reference", models.FloatField(blank=True, null=True)),
            ],
            options={
                "db_table": "pivoted_planningfact",
                "managed": False,
            },
        ),
    ]
