# Generated by Django 5.2.5 on 2025-08-11 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bps", "0002_auto_20250728_0030"),
    ]

    operations = [
        migrations.AddField(
            model_name="planninglayoutdimension",
            name="group_priority",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="1,2,3… to enable nested row grouping (lower = outer); leave blank to not group by this dimension.",
                null=True,
            ),
        ),
    ]
