# Generated by Django 5.2.1 on 2025-07-11 04:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bps", "0002_rename_title_planninglayout_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Position",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=20, unique=True)),
                ("name", models.CharField(max_length=50)),
                ("description", models.TextField(blank=True)),
                (
                    "order",
                    models.IntegerField(
                        default=0, help_text="Controls ordering in UIs"
                    ),
                ),
                ("skill_group", models.CharField(max_length=50)),
                ("level", models.CharField(max_length=20)),
                ("fte", models.FloatField(default=1.0)),
                ("is_open", models.BooleanField(default=False)),
                (
                    "year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="bps.year"
                    ),
                ),
            ],
            options={
                "ordering": ["year__code", "order", "code"],
                "abstract": False,
                "unique_together": {("year", "code")},
            },
        ),
        migrations.CreateModel(
            name="RateCard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("skill_group", models.CharField(max_length=50)),
                (
                    "vendor_type",
                    models.CharField(
                        choices=[("CON", "Contractor"), ("MSP", "MSP")], max_length=20
                    ),
                ),
                ("country", models.CharField(max_length=50)),
                (
                    "efficiency_factor",
                    models.DecimalField(
                        decimal_places=2, help_text="0.00–1.00", max_digits=5
                    ),
                ),
                ("hourly_rate", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="bps.year"
                    ),
                ),
            ],
            options={
                "ordering": ["year__code", "skill_group", "vendor_type", "country"],
                "unique_together": {("year", "skill_group", "vendor_type", "country")},
            },
        ),
    ]
