# Generated by Django 5.2.5 on 2025-08-10 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bps", "0003_pivotedplanningfact"),
    ]

    operations = [
        migrations.AddField(
            model_name="planningdimension",
            name="is_header",
            field=models.BooleanField(default=False),
        ),
    ]
