# Generated by Django 5.2.1 on 2025-07-11 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bps", "0003_position_ratecard"),
    ]

    operations = [
        migrations.AlterField(
            model_name="position",
            name="code",
            field=models.CharField(max_length=20),
        ),
    ]
