# Generated by Django 5.2.5 on 2025-08-10 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bps", "0004_planningdimension_is_header"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="planningdimension",
            name="is_header",
        ),
        migrations.AddField(
            model_name="planninglayoutdimension",
            name="is_header",
            field=models.BooleanField(
                default=False,
                help_text="If true, this dimension is selected in the header (BW-BPS style) and should not appear as a lead column in the manual grid.",
            ),
        ),
    ]
