# Generated by Django 5.2.5 on 2025-08-10 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bps", "0005_remove_planningdimension_is_header_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="keyfigure",
            name="display_decimals",
            field=models.PositiveSmallIntegerField(
                default=2,
                help_text="Number of decimal places to show for this key figure in grids and totals.",
            ),
        ),
    ]
